### ISSUE TITLE
Perl dependencies

### ISSUE THREAD

**Issue by edescourtis** [cern-mig/python-simplevisor#1]
It seems having Perl as a dependencies causes deployment issues. It would be nice if some other format could be supported. Like YAML, JSON or even XML.

**Comment by LionelCons** [comment]
JSON support should be trivial to add. Would this solve your dependency problem?

**Comment by edescourtis** [comment]
Yes definitely!

**Comment by LionelCons** [comment]
Please try the latest commit and its --conftype option. If this is OK, it will be part of the next simplevisor version.

**Comment by edescourtis** [comment]
Perfect I can't thank you enough!

I will let you know if I run into any issues.

Thanks again!
